import {objectForEach} from "@/utils/object";

/**
 * Builds getters for a given function so I can be lazy and not type them myself.
 *
 * @param component {VueComponent} The component to add the getters to.
 * @param idValues {Object} An id object to iterate over and build getters from.
 * @param baseGetter {Function} Base getter function to build from.
 */
export function buildGetters(component, idValues, baseGetter) {
    if (idValues !== undefined) {
        objectForEach(idValues, key => {
            component[key] = baseGetter(key);
        });
    }
}

/**
 * Calculates the amount of resource generated by a set of buildings.
 *
 * @param buildings {Object} Object with building properties to calculate the perSecond value of.
 * @returns {number} The amount generated per second by the set of buildings.
 */
export function calculatePerSecond(buildings) {
    let perSecond = 0;
    objectForEach(buildings, buildingId=> {
        perSecond += buildings[buildingId].perSecond;
    });
    return perSecond;
}